### ISSUE TITLE
修正：Part 2: Tailwind CSS

### ISSUE THREAD

**Issue by Joshua0128** [Ruheng026/Code-Your-Stage-b10705026#1]
待修正：Part 2: Tailwind CSS

LineChart 高度要符合卡片高度（或至少畫面上看起來要近似作業題目截圖）
其他部分都完成了！

Due Time : 9/18 23:59
有問題就在DC發問喔！只差一點了！ 加油！

**Comment by Ruheng026** [comment]
嗨！我調整好了！再麻煩幫我看看這樣是否正確～感謝

**Comment by Joshua0128** [comment]
恭喜你通過囉！
